### PR TITLE
Change order of model template cards in ModelTrainDialog

### LINKED ISSUE #953: Surprising order of the available models
### 🧩 Issue type

Bug 🐞

### 📄 Description

Checked only for the classification. Probably needs to be checked for other project types as well.
In 2.11.0 we have:

Image

In 2.12.0 we have:

Image

1. The default model is shown as the 3rd on the list.
2. The deprecated model is shown in the end of the list.

### 📋 Steps to reproduce (if applicable)

_No response_

### 💻 Expected behavior

_No response_

### 🖼️ Screenshots, video recordings or logs

_No response_

### 📦 Geti version

2.12.0

### Hardware

_No response_

### 🖥️ Operating System

_No response_

### Browser (if applicable)

_No response_

### Python Version (if relevant)

_No response_

### ➕ Additional context

_No response_

### PR DESCRIPTION
**Pull request by romanowska**
## 📝 Description

Change order of model template cards in ModelTrainDialog - Balance should be first.

Screenshot 2025-08-04 at 10 14 21
Screenshot 2025-08-06 at 09 47 05

## ✨ Type of Change

Select the type of change your PR introduces:

- [x] 🐞 **Bug fix** – Non-breaking change which fixes an issue
- [ ] 🚀 **New feature** – Non-breaking change which adds functionality
- [ ] 🔨 **Refactor** – Non-breaking change which refactors the code base
- [ ] 💥 **Breaking change** – Changes that break existing functionality
- [ ] 📚 **Documentation update**
- [ ] 🔒 **Security update**
- [ ] 🧪 **Tests**

## 🧪 Testing Scenarios

Describe how the changes were tested and how reviewers can test them too:

- [x] ✅ Tested manually
- [ ] 🤖 Run automated end-to-end tests

## ✅ Checklist

Before submitting the PR, ensure the following:

- [x] 🔍 PR title is clear and meaningful
- [x] ✍️ PR description clearly explains the changes and their reason
- [x] 📝 I have linked the PR to the corresponding GitHub Issues, if any
- [ ] 💬 I have commented my code, especially in hard-to-understand areas
- [ ] 📄 I have made corresponding changes to the documentation
- [ ] ✅ I have added tests that prove my fix is effective or my feature works

### CODE REVIEW

File: web_ui/src/pages/project-details/components/project-models/train-model-dialog/advanced-settings/model-architectures/model-architectures-main-content.component.tsx [hunk 1]
```diff
@@ -43,7 +43,7 @@ export const ModelArchitecturesMainContent: FC<ModelArchitecturesMainContentProp
     }
 
     const [sortedOtherAlgorithms, sortedRecommendedAlgorithms] = moveActiveArchitectureToBeRightAfterRecommended(
-        recommendedAlgorithms,
+        recommendedAlgorithms.reverse(),
```
Comment (dwesolow) [inline web_ui/src/pages/project-details/components/project-models/train-model-dialog/advanced-settings/model-architectures/model-architectures-main-content.component.tsx]: Why do we need to reverse?

File: web_ui/src/pages/project-details/components/project-models/train-model-dialog/model-types/model-types-list.component.tsx [hunk 2]
```diff
@@ -26,7 +26,7 @@ const getBaseAlgorithms = (
     const speed = algorithms.find((algorithm) => algorithm.performanceCategory === PerformanceCategory.SPEED);
     const balance = algorithms.find((algorithm) => algorithm.performanceCategory === PerformanceCategory.BALANCE);
 
-    const baseAlgorithms = [accuracy, speed, balance].filter(Boolean) as SupportedAlgorithm[];
+    const baseAlgorithms = [balance, accuracy, speed].filter(Boolean) as SupportedAlgorithm[];
```
Comment (jpggvilaca) [inline web_ui/src/pages/project-details/components/project-models/train-model-dialog/model-types/model-types-list.component.tsx]: shouldnt the reverse be `[balance, speed, accuracy]`?

File: web_ui/src/pages/project-details/components/project-models/train-model-dialog/advanced-settings/model-architectures/model-architectures-main-content.component.tsx (hunk 1 above)
Comment (MarkRedeman) [reply web_ui/src/pages/project-details/components/project-models/train-model-dialog/advanced-settings/model-architectures/model-architectures-main-content.component.tsx]: The backend sends us the algorithms in the order that they were created (or so I assume, the deprecated ones are always on top) so this will fix the ordering.

However I think it would be better for us to explicitly sort out the deprecated ones to the bottom inside of `moveActiveArchitectureToBeRightAfterRecommended`.
When sorting by relevance I think we should sort the `otherAlgorithms` based on their lifecycle: `[LifecycleStage.ACTIVE, LifecycleStage.ACTIVE, LifecycleStage.DEPRECATED, LifecycleStage.OBSOLETE]`. 
This way if in the future other the order from the backend changes we will keep showing the same order in the UI.

File: web_ui/src/pages/project-details/components/project-models/train-model-dialog/model-types/model-types-list.component.tsx (hunk 2 above)
Comment (romanowska) [reply web_ui/src/pages/project-details/components/project-models/train-model-dialog/model-types/model-types-list.component.tsx]: the input i got was to have balance first but of course i can change it to `[balance, speed, accuracy]`

File: web_ui/src/pages/project-details/components/project-models/train-model-dialog/advanced-settings/model-architectures/model-architectures-main-content.component.tsx (hunk 1 above)
Comment (romanowska) [reply web_ui/src/pages/project-details/components/project-models/train-model-dialog/advanced-settings/model-architectures/model-architectures-main-content.component.tsx]: ok, i'll make it explicit

Comment (romanowska) [reply web_ui/src/pages/project-details/components/project-models/train-model-dialog/advanced-settings/model-architectures/model-architectures-main-content.component.tsx]: updated

File: web_ui/src/pages/project-details/components/project-models/train-model-dialog/model-types/model-types-list.component.tsx (hunk 2 above)
Comment (romanowska) [reply web_ui/src/pages/project-details/components/project-models/train-model-dialog/model-types/model-types-list.component.tsx]: updated

**Review by dwesolow — DISMISSED** [review]

**Review by jpggvilaca — APPROVED** [review]

**Review by dwesolow — APPROVED** [review]
