### PR TITLE
Add component test of augmentation parameters and add minor fixes

### LINKED ISSUE #978: Introduce configurable augmentations for all supervised tasks
Geti 2.12 exposed augmentation parameters for the classification task; the goal now is to do the same for all other tasks

### PR DESCRIPTION
**Pull request by romanowska**
## 📝 Description

- Addressing comments from https://github.com/open-edge-platform/geti/pull/1250
- change type of minValue from `number` to `number | null`

## ✨ Type of Change

Select the type of change your PR introduces:

- [ ] 🐞 **Bug fix** – Non-breaking change which fixes an issue
- [ ] 🚀 **New feature** – Non-breaking change which adds functionality
- [x] 🔨 **Refactor** – Non-breaking change which refactors the code base
- [ ] 💥 **Breaking change** – Changes that break existing functionality
- [ ] 📚 **Documentation update**
- [ ] 🔒 **Security update**
- [x] 🧪 **Tests**

## 🧪 Testing Scenarios

Describe how the changes were tested and how reviewers can test them too:

- [x] ✅ Tested manually
- [ ] 🤖 Run automated end-to-end tests

## ✅ Checklist

Before submitting the PR, ensure the following:

- [x] 🔍 PR title is clear and meaningful
- [x] ✍️ PR description clearly explains the changes and their reason
- [ ] 📝 I have linked the PR to the corresponding GitHub Issues, if any
- [x] 💬 I have commented my code, especially in hard-to-understand areas
- [ ] 📄 I have made corresponding changes to the documentation
- [x] ✅ I have added tests that prove my fix is effective or my feature works

### CODE REVIEW

File: web_ui/src/pages/project-details/components/project-models/train-model-dialog/advanced-settings/ui/range-parameter-field.component.tsx [hunk 1]
```diff
@@ -54,21 +54,21 @@ export const RangeParameterField: FC<RangeParameterFieldProps> = ({
...
-        if (end - start > fieldStep) {
+        if (end - start >= fieldStep) {
             setParameterValue({ start, end });
             onChange([start, end]);
         }
     };
 
     return (
-        <Flex gap={'size-100'}>
+        <Flex gap={'size-100'} aria-label={name}>
```
Comment (dwesolow) [inline web_ui/src/pages/project-details/components/project-models/train-model-dialog/advanced-settings/ui/range-parameter-field.component.tsx]: IIRC flex does not have `aria-label`, could u please double check it?

File: web_ui/src/core/configurable-parameters/dtos/configuration.interface.ts [hunk 2]
```diff
@@ -10,7 +10,7 @@ interface ParameterBaseDTO {
 interface NumberParameterDTO extends ParameterBaseDTO {
     type: 'int' | 'float';
     value: number;
-    min_value: number;
+    min_value: number | null;
```
Comment (dwesolow) [inline web_ui/src/core/configurable-parameters/dtos/configuration.interface.ts:13]: When `min_value` can be `null`?

File: web_ui/tests/features/project-models/train-model.spec.ts [hunk 3]
```diff
@@ -169,9 +172,39 @@ test.describe('Train model', () => {
...
+            await expect(page.getByRole('slider', { name: 'Minimum Change Brightness' })).toHaveValue('0.875');
+            await expect(page.getByRole('slider', { name: 'Maximum Change Brightness' })).toHaveValue('1.125');
+
+            const brightnessStart = page.getByRole('button', {
+                name: 'Increase Change Brightness range start range value',
+            });
+            await brightnessStart.click();
+
+            const brightnessSlider = page.getByLabel('Change Brightness range value');
+            brightnessSlider.click();
```
Comment (dwesolow) [inline web_ui/tests/features/project-models/train-model.spec.ts]: Missing `await`?

File: web_ui/tests/features/project-models/train-model.spec.ts [hunk 4]
```diff
@@ -398,6 +436,33 @@ test.describe('Train model', () => {
...
```
Comment (dwesolow) [inline web_ui/tests/features/project-models/train-model.spec.ts]: Same here, await?

**Review by pplaskie — DISMISSED** [review]

File: web_ui/src/core/configurable-parameters/dtos/configuration.interface.ts (hunk 2 above)
Comment (romanowska) [reply web_ui/src/core/configurable-parameters/dtos/configuration.interface.ts:13]: for `Random Affine Maximum shear degree`, `Gaussian noise mean`

File: web_ui/src/pages/project-details/components/project-models/train-model-dialog/advanced-settings/ui/range-parameter-field.component.tsx (hunk 1 above)
Comment (romanowska) [reply web_ui/src/pages/project-details/components/project-models/train-model-dialog/advanced-settings/ui/range-parameter-field.component.tsx]: it doesn't. updated

File: web_ui/tests/features/project-models/train-model.spec.ts (hunk 3 above)
Comment (romanowska) [reply web_ui/tests/features/project-models/train-model.spec.ts]: updated

File: web_ui/tests/features/project-models/train-model.spec.ts (hunk 4 above)
Comment (romanowska) [reply web_ui/tests/features/project-models/train-model.spec.ts]: updated

**Review by pplaskie — APPROVED** [review]

**Review by MarkRedeman — APPROVED** [review]
