### PR TITLE
ITEP-32025 Improve FuxNotification component [PART 1]

### LINKED ISSUE #918: Move from CoachMark to FuxNotification
Motivation:

This bug was brought to our attention - dismiss button is unreachable, notification should flip when there's not enough space to show it.

Image

As the CoachMark component doesn't support flipping, after a conversation there was a decision to resign from it and use FuxNotification instead, which is using Popover underneath, supporting automatic notification flipping.

The previous issue with Popover was that it is closing automatically which was not what we wanted. In the meantime we discovered that adding isKeyboardDismissDisabled prevents that default behaviour and is not blocking us from using it anymore.

To do:

1. Add isKeyboardDismissDisabled to FuxNotification component to prevent it from closing the notification when clicking/tapping in the background - only close button, dismiss button or dismiss all should do that.
2. Change all occurances of CoachMark to use FuxNotification instead
3. Fix tests
4. Fix Learn more button on CreditBalanceButton notification: 1. wrong link 2. it should be displayed only for the project it concerns

Known issue:

Popover implementation calculates the tip position automatically which sometimes may be different from what we want but overall the pros are stronger than cons for using it as implementation.

### PR DESCRIPTION
**Pull request by romanowska**
## 📝 Description

Improve FuxNotification component to better resemble the soon-to-be deprecated CoachMark component. On this PR only the case of notification without the Dismiss all option was improved. The existing Credit Button notification was fixed to correctly use the new implementation.

Screenshot 2025-07-10 at 12 47 57

On next PRs:
Fix implementation for more advanced notifications
Use FuxNotification implementation instead of CoachMark

JIRA: ITEP-32025

## ✨ Type of Change

Select the type of change your PR introduces:

- [ ] 🐞 **Bug fix** – Non-breaking change which fixes an issue
- [ ] 🚀 **New feature** – Non-breaking change which adds functionality
- [x] 🔨 **Refactor** – Non-breaking change which refactors the code base
- [ ] 💥 **Breaking change** – Changes that break existing functionality
- [ ] 📚 **Documentation update**
- [ ] 🔒 **Security update**
- [ ] 🧪 **Tests**

## 🧪 Testing Scenarios

Describe how the changes were tested and how reviewers can test them too:

- [x] ✅ Tested manually
- [ ] 🤖 Run automated end-to-end tests

## ✅ Checklist

Before submitting the PR, ensure the following:

- [x] 🔍 PR title is clear and descriptive
- [x] 📝 For internal contributors: If applicable, include the JIRA ticket number (e.g., ITEP-123456) in the PR **title**. Do **not** include full URLs
- [ ] 💬 I have commented my code, especially in hard-to-understand areas
- [ ] 📄 I have made corresponding changes to the documentation
- [ ] ✅ I have added tests that prove my fix is effective or my feature works

### CODE REVIEW

File: web_ui/src/shared/components/header/credit-balance/credit-balance-button.component.tsx [hunk 1]
```diff
@@ -117,8 +117,10 @@ const CreditBalanceButtonFuxNotification = ({ isDarkMode }: { isDarkMode: boolea
 
             {isFirstAutoTrainedProject ? (
                 <FuxNotification
+                    settingsKey={FUX_NOTIFICATION_KEYS.CREDIT_BALANCE_BUTTON}
                     state={fuxState}
-                    docUrl={activeUser?.isAdmin ? paths.account.usage({ organizationId }) : undefined}
+                    // todo: Use roles in combination with useCheckPermission instead
```
Comment (jpggvilaca) [inline web_ui/src/shared/components/header/credit-balance/credit-balance-button.component.tsx]: [Question] Why not make this change now?

File: web_ui/src/shared/components/header/credit-balance/fux-notification/fux-notification.component.tsx [hunk 2]
```diff
@@ -3,22 +3,82 @@
...
+                        aria-label={'Dismiss help dialog'}
+                        UNSAFE_className={classes.close}
+                    >
+                        <Close />
+                    </ActionButton>
+                </View>
+            </CustomPopover>
+        );
+    }
+    // todo: not implemented anywhere yet, to do in next PR
```
Comment (jpggvilaca) [inline web_ui/src/shared/components/header/credit-balance/fux-notification/fux-notification.component.tsx]: could you elaborate on this one?

File: web_ui/src/shared/components/header/credit-balance/fux-notification/fux-notification.module.scss [hunk 3]
```diff
@@ -7,12 +7,82 @@
     & [class*='tip-triangle'] {
         fill: #89ad4e !important;
     }
+
+    margin-top: 5px !important;
```
Comment (jpggvilaca) [inline web_ui/src/shared/components/header/credit-balance/fux-notification/fux-notification.module.scss]: [Nitpick] Use `--spectrum-global-dimension-size-65`

File: web_ui/src/shared/components/header/credit-balance/fux-notification/utils.ts [hunk 4]
```diff
@@ -0,0 +1,115 @@
...
+interface FuxNotificationData {
+    header: string | undefined;
+    description: string;
+    docUrl: DocsUrl | undefined;
+    nextStepId: FUX_NOTIFICATION_KEYS | undefined;
+    previousStepId: FUX_NOTIFICATION_KEYS | undefined;
+    showDismissAll: boolean;
+}
+
+export const getFuxNotificationData = (fuxNotificationId: string): FuxNotificationData => {
```
Comment (jpggvilaca) [inline web_ui/src/shared/components/header/credit-balance/fux-notification/utils.ts]: [Question] Why do we need this new util?
[Suggestion] This shouldn't live here. This handles keys unrelated with credit system

File: web_ui/src/shared/components/header/credit-balance/credit-balance-button.component.tsx (hunk 1 above)
Comment (romanowska) [reply web_ui/src/shared/components/header/credit-balance/credit-balance-button.component.tsx]: agree, i'll do it now

File: web_ui/src/shared/components/header/credit-balance/fux-notification/fux-notification.component.tsx (hunk 2 above)
Comment (romanowska) [reply web_ui/src/shared/components/header/credit-balance/fux-notification/fux-notification.component.tsx]: FuxNotification now if used only in the CreditBalanceButton component, where it uses only the scenario where Dismiss all option is not used. So this case (for now) never happens. When I implement it, I'll also make a change so all the current CoachMarks use FuxNotification instead.

File: web_ui/src/shared/components/header/credit-balance/fux-notification/utils.ts (hunk 4 above)
Comment (romanowska) [reply web_ui/src/shared/components/header/credit-balance/fux-notification/utils.ts]: A to your Q - we used this util for CoachMark, I moved it here so it's close to the FuxNotification, all things CoachMark will eventually be deleted
I agree with this suggestion. FuxNotification should be moved, I'll do that in this PR.

File: web_ui/src/shared/components/header/credit-balance/credit-balance-button.component.tsx (hunk 1 above)
Comment (romanowska) [reply web_ui/src/shared/components/header/credit-balance/credit-balance-button.component.tsx]: updated

File: web_ui/src/shared/components/header/credit-balance/fux-notification/fux-notification.module.scss (hunk 3 above)
Comment (romanowska) [reply web_ui/src/shared/components/header/credit-balance/fux-notification/fux-notification.module.scss]: updated

File: web_ui/src/shared/components/header/credit-balance/fux-notification/utils.ts (hunk 4 above)
Comment (romanowska) [reply web_ui/src/shared/components/header/credit-balance/fux-notification/utils.ts]: updated, moved to shared components

**Review by jpggvilaca — APPROVED** [review]

**Review by pplaskie — APPROVED** [review]
