### PR TITLE
Fix name for STFPM optimized model

### LINKED ISSUE #1149: Wrong name for STFPM optimized model
**Steps to reproduce**

1. Create an anomaly detection project
2. Upload enough images for training
3. Train STFPM model
4. After training, open the model detail page

**Expected**

The optimized model (with post-training optimization) is listed as `STFPM OpenVINO INT8`.

**Actual**

The name is incorrect: `STINT8`.

Image

I didn't take a look at the source code, but I'm pretty sure the faulty logic looks like follows 😆 
```
optimized_model_name = base_model_name.split("FP")[0] + " INT8"
```
That would explain why the bug only affects this model architecture.

### PR DESCRIPTION
**Pull request by romanowska**
## 📝 Description

Fix name for STFPM optimized model

Before:
Screenshot 2025-09-01 at 10 29 44

After:
Screenshot 2025-09-01 at 10 52 00

## ✨ Type of Change

Select the type of change your PR introduces:

- [x] 🐞 **Bug fix** – Non-breaking change which fixes an issue
- [ ] 🚀 **New feature** – Non-breaking change which adds functionality
- [ ] 🔨 **Refactor** – Non-breaking change which refactors the code base
- [ ] 💥 **Breaking change** – Changes that break existing functionality
- [ ] 📚 **Documentation update**
- [ ] 🔒 **Security update**
- [ ] 🧪 **Tests**

## 🧪 Testing Scenarios

Describe how the changes were tested and how reviewers can test them too:

- [x] ✅ Tested manually
- [ ] 🤖 Run automated end-to-end tests

## ✅ Checklist

Before submitting the PR, ensure the following:

- [x] 🔍 PR title is clear and meaningful
- [x] ✍️ PR description clearly explains the changes and their reason
- [x] 📝 I have linked the PR to the corresponding GitHub Issues, if any
- [ ] 💬 I have commented my code, especially in hard-to-understand areas
- [ ] 📄 I have made corresponding changes to the documentation
- [ ] ✅ I have added tests that prove my fix is effective or my feature works

### CODE REVIEW

File: web_ui/src/pages/project-details/components/project-model/model-variants/tabs/open-vino-tab-models.component.tsx [hunk 1]
```diff
@@ -34,12 +34,11 @@ export const OpenVinoTabModels: FC<OpenvinoTabModelsProps> = ({
     const openVinoModels = models.filter((model) => model.modelFormat !== ModelFormat.ONNX);
 
     const firstOptimizedModel = openVinoModels.filter(isNotBaselineModel).at(0);
-
     const emptyPOTModel: OptimizedModel | undefined =
         firstOptimizedModel === undefined
             ? undefined
             : getMockedOptimizedModel({
-                  modelName: firstOptimizedModel.modelName.replace(/FP.*/, 'INT8') ?? '',
+                  modelName: firstOptimizedModel.modelName.replace(/OpenVINO.*/, 'INT8') ?? '',
```
Comment (MarkRedeman) [inline web_ui/src/pages/project-details/components/project-model/model-variants/tabs/open-vino-tab-models.component.tsx]: Should this not also still say `OpenVINO`? E.g. have,

```suggestion
                  modelName: firstOptimizedModel.modelName.replace(/OpenVINO.*/, 'OpenVINO INT8') ?? '',
```

Comment (romanowska) [reply web_ui/src/pages/project-details/components/project-model/model-variants/tabs/open-vino-tab-models.component.tsx]: In the ticket https://github.com/open-edge-platform/geti/issues/1149 it says `STFPM INT8` but i'll double check with Leo

Comment (romanowska) [reply web_ui/src/pages/project-details/components/project-model/model-variants/tabs/open-vino-tab-models.component.tsx]: Ok Leo said to change it to `STFPM OpenVINO INT8`. Thanks Mark! :)

Comment (leoll2) [reply web_ui/src/pages/project-details/components/project-model/model-variants/tabs/open-vino-tab-models.component.tsx]: my bad, it should be `STFPM OpenVINO INT8`, consistently with the other names

**Review by MarkRedeman — APPROVED** [review]

**Review by jpggvilaca — APPROVED** [review]
