### PR TITLE
Fix ensuring proper display of range parameters

### LINKED ISSUE #1289: Ranges in model metrics are not displayed properly
### 🧩 Issue type

Bug 🐞

### 📄 Description

See attached image. Scaling ratio (and other ranges) is displayed as 0.51.5

Image

### 📋 Steps to reproduce (if applicable)

Click on a trained model and go to the parameters tab. 

### 💻 Expected behavior

_No response_

### 🖼️ Screenshots, video recordings or logs

_No response_

### 📦 Geti version

2.12

### Hardware

_No response_

### 🖥️ Operating System

_No response_

### Browser (if applicable)

_No response_

### Python Version (if relevant)

_No response_

### ➕ Additional context

_No response_

### PR DESCRIPTION
**Pull request by romanowska**
## 📝 Description

Fix ensuring proper display of range parameters
Screenshot 2025-09-25 at 13 41 45

## ✨ Type of Change

Select the type of change your PR introduces:

- [x] 🐞 **Bug fix** – Non-breaking change which fixes an issue
- [ ] 🚀 **New feature** – Non-breaking change which adds functionality
- [ ] 🔨 **Refactor** – Non-breaking change which refactors the code base
- [ ] 💥 **Breaking change** – Changes that break existing functionality
- [ ] 📚 **Documentation update**
- [ ] 🔒 **Security update**
- [ ] 🧪 **Tests**

## 🧪 Testing Scenarios

Describe how the changes were tested and how reviewers can test them too:

- [x] ✅ Tested manually
- [ ] 🤖 Run automated end-to-end tests

## ✅ Checklist

Before submitting the PR, ensure the following:

- [x] 🔍 PR title is clear and meaningful
- [x] ✍️ PR description clearly explains the changes and their reason
- [x] 📝 I have linked the PR to the corresponding GitHub Issues, if any
- [ ] 💬 I have commented my code, especially in hard-to-understand areas
- [ ] 📄 I have made corresponding changes to the documentation
- [ ] ✅ I have added tests that prove my fix is effective or my feature works

### CODE REVIEW

**Review by pplaskie — DISMISSED** [review]

File: web_ui/src/pages/project-details/components/project-models/train-model-dialog/advanced-settings/ui/parameters.component.tsx [hunk 1]
```diff
@@ -87,6 +87,14 @@ export const ParameterReadOnlyValue = ({ value, name }: ParameterReadOnlyValuePr
         return <span aria-label={name}>{value ? 'On' : 'Off'}</span>;
     }
 
+    if (isArray(value)) {
```
Comment (dwesolow) [inline web_ui/src/pages/project-details/components/project-models/train-model-dialog/advanced-settings/ui/parameters.component.tsx]: I think it would be good to make sure if there are two items in the array as well.

Comment (pplaskie) [reply web_ui/src/pages/project-details/components/project-models/train-model-dialog/advanced-settings/ui/parameters.component.tsx]: Is it an option to get array but with different number of items than 2?
Or do you want to be sure sure that nothing will break if backend would send not expected data?

Comment (dwesolow) [reply web_ui/src/pages/project-details/components/project-models/train-model-dialog/advanced-settings/ui/parameters.component.tsx]: It should not be the case IIRC but just in case when backend breaks (advantage of this would be that we don't need to check other parts of the training parameters feature to figure out how many items array can have).

Comment (romanowska) [reply web_ui/src/pages/project-details/components/project-models/train-model-dialog/advanced-settings/ui/parameters.component.tsx]: i'll add extra condition to check length of the array

**Review by pplaskie — APPROVED** [review]

**Review by jpggvilaca — APPROVED** [review]
