### PR TITLE
Fix Create New Project dialog styles

### LINKED ISSUE #938: create new project dialog layout
STR:
* Press "Create project"
* Resize the window

Expected results: 
* Dialog is centered

Current results:
* Dialog is not centered

Image
Image

### PR DESCRIPTION
**Pull request by romanowska**
## 📝 Description

Fix the styles to match previous design and display Divider

before:
Screenshot 2025-08-08 at 09 34 58

after:
Screenshot 2025-08-08 at 09 32 11

## ✨ Type of Change

Select the type of change your PR introduces:

- [x] 🐞 **Bug fix** – Non-breaking change which fixes an issue
- [ ] 🚀 **New feature** – Non-breaking change which adds functionality
- [ ] 🔨 **Refactor** – Non-breaking change which refactors the code base
- [ ] 💥 **Breaking change** – Changes that break existing functionality
- [ ] 📚 **Documentation update**
- [ ] 🔒 **Security update**
- [ ] 🧪 **Tests**

## 🧪 Testing Scenarios

Describe how the changes were tested and how reviewers can test them too:

- [x] ✅ Tested manually
- [ ] 🤖 Run automated end-to-end tests

## ✅ Checklist

Before submitting the PR, ensure the following:

- [x] 🔍 PR title is clear and meaningful
- [x] ✍️ PR description clearly explains the changes and their reason
- [x] 📝 I have linked the PR to the corresponding GitHub Issues, if any
- [ ] 💬 I have commented my code, especially in hard-to-understand areas
- [ ] 📄 I have made corresponding changes to the documentation
- [ ] ✅ I have added tests that prove my fix is effective or my feature works

### CODE REVIEW

**Review by pplaskie — DISMISSED** [review]

File: web_ui/src/pages/create-project/components/project-labels-management/project-labels-management.component.tsx [hunk 1]
```diff
@@ -95,7 +95,7 @@ export const ProjectLabelsManagement = ({
     return (
         <SliderAnimation
             animationDirection={animationDirection}
-            style={{ height: '100%', display: 'flex', flexDirection: 'column' }}
+            style={{ height: '52vh', display: 'flex', flexDirection: 'column' }}
```
Comment (dwesolow) [inline web_ui/src/pages/create-project/components/project-labels-management/project-labels-management.component.tsx]: We should not set the height for the content but for the dialog itself. Please take a look at a difference between these two:
1. `minHeight` set on the dialog.
image

2. `height` set on the content.
image

Comment (romanowska) [reply web_ui/src/pages/create-project/components/project-labels-management/project-labels-management.component.tsx]: form the offline conversation i understood we want for steps 2 and 3 to have the same height to avoid the "jumping" effect when changing between the steps and it works. what's wrong with the solution?

Comment (dwesolow) [reply web_ui/src/pages/create-project/components/project-labels-management/project-labels-management.component.tsx]: This solution introduces more empty space in the project task type selection, it introduces basically the same thing that we remove for the project name step.
You can set the `minHeight` for the dialog only for all but not project name step, e.g. `currentStep === STEPS.NAME_PROJECT ? undefined : 52vh`

Comment (romanowska) [reply web_ui/src/pages/create-project/components/project-labels-management/project-labels-management.component.tsx]: ok, so then jumping between 2 and 3 stays because we don't want the empty space in the step 2 which has a smaller content height than step 3

**Review by pplaskie — APPROVED** [review]

**Review by dwesolow — APPROVED** [review]
